apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: production
  name: acme-node
spec:
  selector:
    matchLabels:
      environment: production
  template:
    metadata:
      labels:
        environment: production
    spec:
      containers:
        - name: app
          env:
            - name: GREETING_SERVICE_URL
              value: greeting-service.greeting-service-production.svc.cluster.local:50051
            - name: PERSON_SERVICE_URL
              value: person-service.person-service-production.svc.cluster.local:50051
