apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: local
  name: acme-node
spec:
  selector:
    matchLabels:
      environment: local
  template:
    metadata:
      labels:
        environment: local
    spec:
      containers:
        - name: app
          env:
            - name: LOG_LEVEL
              value: debug
            - name: OTEL_LOG_LEVEL
              value: debug
            - name: OTEL_TRACES_EXPORTER
              value: console
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: GREETING_SERVICE_URL
              value: greeting-service.greeting-service-local.svc.cluster.local:50051
            - name: PERSON_SERVICE_URL
              value: person-service.person-service-local.svc.cluster.local:50051
