apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: local
  name: acme-node
spec:
  selector:
    matchLabels:
      environment: local
  template:
    metadata:
      labels:
        environment: local
    spec:
      containers:
        - name: app
          env:
            - name: LOG_LEVEL
              value: DEBUG
