apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: preview
  name: acme-node
spec:
  selector:
    matchLabels:
      environment: preview
  template:
    metadata:
      labels:
        environment: preview
    spec:
      containers:
        - name: app
          env:
            - name: LOG_LEVEL
              value: DEBUG
            - name: GREETING_SERVICE_URL
              value: greeting-service.greeting-service-sandbox.svc.cluster.local:50051
            - name: PERSON_SERVICE_URL
              value: person-service.person-service-sandbox.svc.cluster.local:50051
