---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - app.yaml

patches:
  - path: deployment.yaml
  - target:
      kind: Service
      name: acme-node
    patch: |-
      - op: add
        path: /spec/selector/environment
        value: preview
