---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acme-node
  name: acme-node
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: acme-node
  template:
    metadata:
      labels:
        app: acme-node
    spec:
      containers:
        - name: app
          image: acme-node
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: production
            - name: OTEL_SERVICE_NAME
              value: acme-node
            - name: GREETING_SERVICE_URL
              value: greeting-service.greeting-service-local.svc.cluster.local:50051
            - name: PERSON_SERVICE_URL
              value: person-service.person-service-local.svc.cluster.local:50051
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
