---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: acme-node
spec:
  parentRefs:
    - kind: Gateway
      name: http
      namespace: kube-system
  hostnames:
    - localhost
  rules:
    - backendRefs:
        - name: acme-node
          port: 80
