---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: acme-node
spec:
  parentRefs:
    - name: acme-node
      kind: Service
      group: core
      port: 80
  rules: []
