---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml

images:
  - name: acme-node
    newName: ghcr.io/gitops-ci-cd/acme-node
    newTag: f0a4911806965011135aec983dcb5f5d210cdc08
